###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: leaderboard-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: leaderboard-mailhog
      ports:
        - "8081:8025"

    mysql:
      image: mysql:8.0
      container_name: leaderboard-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "3307:3306"
    redis:
      image: redis:latest
      container_name: leaderboard-redis
      working_dir: /application
      volumes:
        - .:/appliation

    webserver:
      image: nginx:alpine
      container_name: leaderboard-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./ops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"

    php-fpm:
      build: ops/php-fpm
      container_name: leaderboard-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./ops/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

